# Generated by Django 6.0.3 on 2026-05-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0, help_text='Puntos de fidelidad acumulados'),
        ),
    ]
