# Generated by Django 6.0.3 on 2026-04-20 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_picture_customuser_salon_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='salon_gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=100, null=True)),
                ('is_cover', models.BooleanField(default=False, help_text='¿Es la foto principal de la galería?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(limit_choices_to={'role': 'professional'}, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
