# Generated by Django 6.0.3 on 2026-05-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options_remove_post_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Equipo EsteticMe', max_length=150),
        ),
    ]
