# Generated by Django 6.0.3 on 2026-05-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_guest_name_alter_booking_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('completed', 'Terminada'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
    ]
