# Generated by Django 6.0.3 on 2026-05-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
