# Generated by Django 6.0.3 on 2026-05-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_guest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Dinero descontado por los puntos', max_digits=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='points_earned',
            field=models.IntegerField(default=0, help_text='Puntos que ganó por esta reserva'),
        ),
        migrations.AddField(
            model_name='booking',
            name='points_used',
            field=models.IntegerField(default=0, help_text='Puntos que el cliente gastó en esta reserva'),
        ),
    ]
